spring:
  profiles:
    active: "local"
  main:
    banner-mode: "off"

---
spring:
  profiles: local
  h2:
    console:
      enabled: true
      path: /h2
    datasource:
      url: jdbc:h2:file:~/test
      username: sa
      password:
      driverClassName: org.h2.Driver
  # Embedded ActiveMQ Configuration Example
  activemq:
    broker-url: vm://embedded?broker.persistent=false,useShutdownHook=false
    in-memory: true
    non-blocking-redelivery: true
    packages:
      trust-all: false
      trusted: com.qnq.jmsjta
    pool:
      block-if-full: true
      block-if-full-timeout: -1
      enabled: false
      idle-timeout: 30000
      max-connections: 1
      time-between-expiration-check: -1
      use-anonymous-producers: true
      max-sessions-per-connection: 500

    # Spring JMS Settings
    jms:
      listener:
        acknowledge-mode: auto
        auto-startup: true
        concurrency: 5
        max-concurrency: 10
      pub-sub-domain: false
      template:
        default-destination:
        delivery-mode: non_persistent
        priority: 100
        qos-enabled: true
        receive-timeout: 1000
        time-to-live: 36000

---

spring:
  profiles: dev
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: springboot
    password: springboot1
    driver-class-name: oracle.jdbc.OracleDriver

---
spring:
  profiles: production
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: springboot
    password: springboot1
    driver-class-name: oracle.jdbc.OracleDriver


# Logging configuration print only messages for tutorial purposes
logging:
  level:
    .: error
    org.springframework: ERROR
    com.qnq.jmsjta: ERROR